spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_CLIENT_ID:your-client-id}
            client-secret: ${OAUTH2_CLIENT_SECRET:your-client-secret}
            scope: user:email, read:user
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: email, profile

server:
  port: 8080

